# Generated by Django 4.1.7 on 2023-05-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libelle')),
            ],
            options={
                'verbose_name_plural': 'Commune',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=70, unique=True, verbose_name='Contact')),
            ],
            options={
                'verbose_name_plural': 'Filiere',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='Libelle')),
            ],
            options={
                'verbose_name_plural': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, verbose_name='Libellé')),
            ],
            options={
                'verbose_name_plural': 'Sexe',
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=70, unique=True, verbose_name='Contact')),
            ],
            options={
                'verbose_name_plural': 'Universités',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libelle')),
            ],
            options={
                'verbose_name_plural': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Ufr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=70, unique=True, verbose_name='Contact')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.universite', verbose_name='Université')),
            ],
            options={
                'verbose_name_plural': 'UFR',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libelle')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.filiere', verbose_name='Filiere')),
            ],
            options={
                'verbose_name_plural': 'Specialité',
            },
        ),
        migrations.CreateModel(
            name='Niveau_Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.niveau', verbose_name='Niveau')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specialite', verbose_name='Specialité')),
            ],
            options={
                'verbose_name_plural': 'Niveau_Specialite',
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ufr', verbose_name='Ufr'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prenom')),
                ('matricule', models.CharField(max_length=150, verbose_name='Matricule')),
                ('lieu_de_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('date_de_naissance', models.DateField(max_length=150, verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=70, unique=True, verbose_name='Contact')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.commune', verbose_name='Commune')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.filiere', verbose_name='Filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.niveau', verbose_name='Niveau')),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sexe', verbose_name='Sexe')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specialite', verbose_name='Specialite')),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ufr', verbose_name='Ufr')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.universite', verbose_name='Universite')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name_plural': 'Etudiant',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ville', verbose_name='Ville'),
        ),
    ]
