# Generated by Django 4.1.7 on 2023-05-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name_plural': 'Filière'},
        ),
    ]
