# Generated by Django 4.1.7 on 2023-05-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_filiere_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='niveau_specialite',
            name='specialite',
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
