# Generated by Django 4.1.7 on 2023-05-30 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='carte_cni',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='cni', verbose_name='Carte CNI'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='carte_etudiant',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='CarteEtudiant', verbose_name="Carte d'étudiant"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=150, verbose_name='Date d\\identification'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='n_cni',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='N°CNI'),
        ),
    ]
